#!/usr/bin/env bash
# Transfers file from client to server using scp command
#Accepts 4 parameters otherwise prints proper usage instructions
#Parameters; file path, server IP, username, private key path
# Transfers file to home directory
# Strict host key checking must be disabled
if [ $# -lt 4 ]; then
     	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
