#!/usr/bin/env bash
# Fizzbuzz with numbers from 1 to 100
# Displays FizzBuzz when the number is a multiple of 3 and 5
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Otherwise, displays the number

counter=1
while [ $counter -le 100 ]
do
	if ! (( counter%15 ))
	then
		echo "FizzBuzz"
	elif ! (( counter% 3 ))
	then
		echo "Fizz"
	elif ! (( counter %5 ))
	then
		echo "Buzz"
	else
		echo "$counter"
	fi
	(( counter++ ))
done
