#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes:
	# display hours from 0 to 12
	# display minutes from 1 to 59

hours=0
minutes=1

while [ $hours -le 12 ]
do
	echo "Hour: $hours"
	(( hours++ ))
	while [ $minutes -le 59 ]
	do
		echo "$minutes"
		(( minutes++ ))
	done
	minutes=1 # resets minutes counter to 1 to allow 2nd while loop to run again, otherwise minutes = 60
done
