#!/usr/bin/env bash
#Bash script that displays:
	#The content of the current directory
	#In a list format
	#Where only the part of the name after the first dash is displayed

list=$(ls)
for i in $list;
do
	echo "$i" | cut -d '-' -f2- # https://linuxhint.com/bash-substring-after-character/
done
